name: HelloPlugin
version: 1.0.0
main: com.ari.myplugin.HelloPlugin
description: My first Paper Plugin
author: WhyNotAri
website: https://papermc.io
api-version: '1.21.11'

commands:
  hello:
    description: It says hello
    usage: /hello