name: MyFirstPlugin
version: 1.0.0
main: com.ari.myplugin.Main
description: Learning how to make Minecraft plugins
author: WhyNotAri
website: https://papermc.io
api-version: '1.21.11'

commands:
  hello:
    description: It says hello
    usage: /hello
  track:
    description: Select a player to track with a compass
    usage: /track <player>