name: HolaPlugin
version: 1.0.0
main: me.ari.holaplugin.HolaPlugin
description: Mi primer plugin en Paper
author: WhyNotAri
website: https://papermc.io
api-version: '1.21.11'

commands:
  hello:
    description: It says hello
    usage: /hello